"""changes to def workouts

Revision ID: 0713245da4ea
Revises: 7eef80ae7fe1
Create Date: 2022-07-22 13:02:31.644250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0713245da4ea'
down_revision = '7eef80ae7fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'name')
    # ### end Alembic commands ###
