"""Updated Workouts scheme

Revision ID: 770bd92cde5e
Revises: 71684ece4104
Create Date: 2022-07-31 17:28:18.905748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770bd92cde5e'
down_revision = '71684ece4104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_column('workout', 'day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('day', sa.INTEGER(), nullable=True))
    op.drop_column('workout', 'due_date')
    # ### end Alembic commands ###
