"""changes to def workouts

Revision ID: fedf21ac2be4
Revises: 0713245da4ea
Create Date: 2022-07-22 13:03:22.880771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fedf21ac2be4'
down_revision = '0713245da4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('workout_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'workout', ['workout_id'], ['id'])
    op.drop_column('session', 'workout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('workout', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'workout', ['workout'], ['id'])
    op.drop_column('session', 'workout_id')
    # ### end Alembic commands ###
